#!/bin/bash

SERVICENET_IP=$(ifconfig etho | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')

cat <<END
# create RSA certs - Server

RANDFILE = ./openssl.rnd

[ req ]
default_bits = 1024
encrypt_key = yes
distinguished_name = req_dn
x509_extensions = cert_type

[ req_dn ]
countryName = Country Name (2 letter code)
countryName_default = US

stateOrProvinceName             = State or Province Name (full name)
stateOrProvinceName_default     = North Carolina

localityName                    = Locality Name (eg, city)
localityName_default            = Apex

organizationName                = Organization Name (eg, company)
organizationName_default        = Physician Care Direct

organizationalUnitName          = Organizational Unit Name (eg, section)
organizationalUnitName_default  = None

commonName                      = Common Name (FQDN of your server)
commonName_default              = $SERVICENET_IP

emailAddress                    = Email Address
emailAddress_default            = bj.lawson@physiciancaredirect.com

[ cert_type ]
nsCertType = server
END
